name: Jeong Ukjae
description: Engineering blog

footer-links:
  email: jeongukjae@gmail.com
  facebook: JeongUkJae
  github: jeongukjae
  linkedin: JeongUkJae
  twitter: jeongukjae
  rss: .
  stackoverflow:

disqus: blog-1fcnjlnavl

google_analytics: UA-88231825-2

url: https://jeongukjae.github.io
baseurl: ""
paginate: 10

permalink: /posts/:title/
version: v1.2.0
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'

sass:
  style: :compressed

plugins:
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate

exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - .vscode
  - .git
  - .gitignore
  - .DS_Store
  - serve.sh
